export interface Protocol {
  name: string;
  description: string;
  docs: string;
  github: string | null;
  category: string;
  groupId: string;
}

export const protocols: Protocol[] = [
  {
    name: "Aave v3",
    description: "Leading decentralized liquidity protocol for borrowing and lending with cross-chain functionality and risk management",
    docs: "https://docs.aave.com/developers/",
    github: "https://github.com/aave/aave-v3-core",
    category: "DeFi",
    groupId: "Aave",
  },
  {
    name: "Alchemy",
    description: "Web3 development platform with node APIs, data APIs, smart wallets, and multi-chain infrastructure across 80+ networks",
    docs: "https://www.alchemy.com/docs",
    github: "https://github.com/alchemyplatform",
    category: "Infrastructure",
    groupId: "Alchemy",
  },
  {
    name: "Aster",
    description: "Decentralized perpetual exchange combining high-leverage trading with yield products and stablecoin offerings",
    docs: "https://docs.asterdex.com/",
    github: "https://github.com/asterdex/",
    category: "DeFi",
    groupId: "Aster",
  },
  {
    name: "Axelar",
    description: "Cross-chain communication protocol enabling secure interoperability and token transfers across blockchains",
    docs: "https://docs.axelar.dev/",
    github: "https://github.com/axelarnetwork",
    category: "Infrastructure",
    groupId: "Axelar",
  },
  {
    name: "Aztec",
    description: "Privacy-focused L2 solution with native zero-knowledge proofs for confidential smart contracts",
    docs: "https://docs.aztec.network/",
    github: "https://github.com/AztecProtocol",
    category: "Privacy",
    groupId: "Aztec",
  },
  {
    name: "Balancer v3",
    description: "Flexible automated market maker with customizable liquidity pools, weighted pools, and boosted pool technology",
    docs: "https://docs.balancer.fi/",
    github: "https://github.com/balancer/balancer-v3-monorepo",
    category: "DeFi",
    groupId: "Balancer-V3",
  },
  {
    name: "Beefy",
    description: "Multi-chain yield optimizer automating compound farming strategies with vault-based yield aggregation",
    docs: "https://docs.beefy.finance/",
    github: "https://github.com/beefyfinance",
    category: "DeFi",
    groupId: "Beefy",
  },
  {
    name: "BENQI",
    description: "Leading DeFi suite on Avalanche with liquid staking, lending and borrowing markets, and validator deployment solutions",
    docs: "https://docs.benqi.fi/",
    github: "https://github.com/Benqi-fi",
    category: "DeFi",
    groupId: "Benqi",
  },
  {
    name: "Centrifuge",
    description: "Pioneering platform for real-world asset tokenization enabling access to structured credit, real estate, and treasuries onchain",
    docs: "https://docs.centrifuge.io/",
    github: "https://github.com/centrifuge/",
    category: "DeFi",
    groupId: "Centrifuge",
  },
  {
    name: "Chainlink",
    description: "Industry-standard oracle platform connecting blockchains to real-world data and enabling cross-chain communication",
    docs: "https://docs.chain.link/",
    github: "https://github.com/smartcontractkit",
    category: "Infrastructure",
    groupId: "ChainLink",
  },
  {
    name: "CIAN",
    description: "DeFi automation protocol with yield optimization strategies, bond management, and yield redistribution infrastructure",
    docs: "https://docs.cian.app/",
    github: "https://github.com/cian-ai/cian-protocol",
    category: "DeFi",
    groupId: "CIAN",
  },
  {
    name: "Circle",
    description: "Blockchain platform providing stablecoin infrastructure, programmable wallets, and cross-chain transfers",
    docs: "https://developers.circle.com/",
    github: "https://github.com/circlefin",
    category: "Infrastructure",
    groupId: "Circle",
  },
  {
    name: "Coinbase CDP",
    description: "Developer platform providing APIs and SDKs for building onchain applications with wallet, payment, and trading services",
    docs: "https://docs.cdp.coinbase.com/",
    github: "https://github.com/coinbase/coinbase-sdk-nodejs",
    category: "Infrastructure",
    groupId: "Coinbase-CDP",
  },
  {
    name: "Compound Finance",
    description: "EVM-compatible lending protocol enabling collateralized borrowing and interest-earning on supplied crypto assets",
    docs: "https://docs.compound.finance/",
    github: "https://github.com/compound-finance",
    category: "DeFi",
    groupId: "Compound-Finance",
  },
  {
    name: "Convex",
    description: "Yield optimization platform built on top of Curve Finance, allowing liquidity providers to earn boosted rewards without locking CRV",
    docs: "https://docs.convexfinance.com/",
    github: "https://github.com/convex-eth",
    category: "DeFi",
    groupId: "Convex",
  },
  {
    name: "Curve Finance",
    description: "Leading AMM optimized for stablecoin swaps and low-slippage trading with innovative liquidity provision mechanisms",
    docs: "https://docs.curve.fi/",
    github: "https://github.com/curvefi",
    category: "DeFi",
    groupId: "Curve-Finance",
  },
  {
    name: "Dinari",
    description: "Tokenized stock platform enabling fractional equity ownership through dShares™ with institutional-grade compliance",
    docs: "https://docs.dinari.com/",
    github: "https://github.com/dinaricrypto",
    category: "DeFi",
    groupId: "Dinari",
  },
  {
    name: "EigenLayer",
    description: "Restaking protocol enabling decentralized services to leverage Ethereum's security",
    docs: "https://docs.eigenlayer.xyz/",
    github: "https://github.com/Layr-Labs/eigencloud-docs",
    category: "Infrastructure",
    groupId: "EigenLayer",
  },
  {
    name: "Equalizer Exchange",
    description: "Decentralized exchange with customizable liquidity pools and advanced trading features",
    docs: "https://docs.equalizer.exchange/",
    github: "https://github.com/Equalizer-Exchange",
    category: "DeFi",
    groupId: "Equalizer-Exchange",
  },
  {
    name: "Ethereum ERCs",
    description: "Standardized smart contract interfaces including token standards and common patterns for Ethereum interoperability",
    docs: "https://eips.ethereum.org/erc",
    github: "https://github.com/ethereum/ercs",
    category: "Standards",
    groupId: "ERCs",
  },
  {
    name: "Ethena",
    description: "Synthetic dollar protocol providing crypto-native stable assets backed by staked ETH and delta-hedging strategies",
    docs: "https://docs.ethena.fi/",
    github: "https://github.com/ethena-labs",
    category: "DeFi",
    groupId: "Ethena",
  },
  {
    name: "Ethers.js",
    description: "Ethereum library for JavaScript and TypeScript with wallet management, providers, and contract interaction",
    docs: "https://docs.ethers.org/",
    github: "https://github.com/ethers-io/ethers.js",
    category: "Tools",
    groupId: "Ethers",
  },
  {
    name: "Euler",
    description: "Modular lending protocol with permissionless market creation and customizable risk parameters for diverse crypto assets",
    docs: "https://docs.euler.finance/",
    github: "https://github.com/euler-xyz",
    category: "DeFi",
    groupId: "Euler",
  },
  {
    name: "EtherFi",
    description: "Liquid restaking protocol enabling non-custodial ETH staking with eETH tokens and native restaking capabilities",
    docs: "https://etherfi.gitbook.io/etherfi/",
    github: "https://github.com/etherfi-protocol",
    category: "DeFi",
    groupId: "Etherfi",
  },
  {
    name: "Falcon",
    description: "Universal collateralization protocol unlocking yield from cryptocurrencies and tokenized real-world assets",
    docs: "https://docs.falcon.finance/",
    github: "https://github.com/falconfinance/",
    category: "DeFi",
    groupId: "Falcon",
  },
  {
    name: "Flaunch",
    description: "Permissionless tokenization protocol with fair launch mechanics and builder-focused revenue sharing",
    docs: "https://docs.flaunch.gg/",
    github: "https://github.com/flayerlabs/flaunchgg-contracts",
    category: "DeFi",
    groupId: "Flaunch",
  },
  {
    name: "Flashbots",
    description: "Research and development organization mitigating negative externalities of MEV through transparent and permissionless infrastructure",
    docs: "https://docs.flashbots.net/",
    github: "https://github.com/flashbots",
    category: "Infrastructure",
    groupId: "Flashbots",
  },
  {
    name: "Fluid",
    description: "Advanced lending protocol with liquidity consolidation, automated limits, and integrated DEX for efficient capital utilization across DeFi",
    docs: "https://docs.fluid.instadapp.io/",
    github: "https://github.com/Instadapp/fluid-contracts-public",
    category: "DeFi",
    groupId: "Fluid",
  },
  {
    name: "Foundry",
    description: "Fast, portable and modular toolkit for Ethereum application development written in Rust",
    docs: "https://getfoundry.sh/",
    github: "https://github.com/foundry-rs/foundry",
    category: "Tools",
    groupId: "Foundry",
  },
  {
    name: "Gelato",
    description: "Web3 cloud platform for smart contract automation, account abstraction, and rollup-as-a-service infrastructure",
    docs: "https://docs.gelato.network/",
    github: "https://github.com/gelatodigital",
    category: "Infrastructure",
    groupId: "Gelato",
  },
  {
    name: "Hardhat",
    description: "Development environment to compile, deploy, test, and debug Ethereum software",
    docs: "https://hardhat.org/docs",
    github: "https://github.com/NomicFoundation/hardhat",
    category: "Tools",
    groupId: "Hardhat",
  },
  {
    name: "HyperLend",
    description: "High-performance lending protocol on Hyperliquid with real-time leverage, dynamic rates, and capital-efficient liquidity",
    docs: "https://docs.hyperlend.finance/",
    github: "https://github.com/hyperlendx",
    category: "DeFi",
    groupId: "HyperLend",
  },
  {
    name: "Hypurr",
    description: "Leveraged lending marketplace on Hyperliquid with clean leverage loops and USDXL synthetic dollar",
    docs: "https://docs.hypurr.fi/",
    github: "https://github.com/lastdotnet/",
    category: "DeFi",
    groupId: "Hypurr",
  },
  {
    name: "JustLend",
    description: "Decentralized lending and borrowing protocol on TRON blockchain with staked TRX and energy rental features",
    docs: "https://docs.justlend.org/developers/contracts_overview/",
    github: "https://github.com/justlend",
    category: "DeFi",
    groupId: "JustLend",
  },
  {
    name: "KernelDAO",
    description: "Restaking infrastructure ecosystem with BNB restaking, ETH liquid restaking (rsETH), and curated reward vaults across DeFi",
    docs: "https://kerneldao.gitbook.io/kernel",
    github: "https://github.com/Kelp-DAO",
    category: "DeFi",
    groupId: "KernelDAO",
  },
  {
    name: "Kinetiq",
    description: "Liquid staking protocol for Hyperliquid with kHYPE tokens and dynamic validator delegation",
    docs: "https://kinetiq.xyz/docs",
    github: "https://github.com/kinetiq-research",
    category: "DeFi",
    groupId: "Kinetiq",
  },
  {
    name: "Lido",
    description: "Leading liquid staking protocol enabling users to earn staking rewards without locking assets or maintaining infrastructure",
    docs: "https://docs.lido.fi/",
    github: "https://github.com/lidofinance/core",
    category: "DeFi",
    groupId: "Lido",
  },
  {
    name: "Liquid Collective",
    description: "Enterprise-grade liquid staking protocol providing institutional access to staking with built-in compliance and slashing coverage",
    docs: "https://docs.liquidcollective.io/",
    github: "https://github.com/liquid-collective",
    category: "DeFi",
    groupId: "Liquid-Collective",
  },
  {
    name: "Liquity",
    description: "Immutable borrowing protocol with user-set interest rates, ETH/LST collateral, and BOLD stablecoin minting",
    docs: "https://docs.liquity.org/",
    github: "https://github.com/liquity",
    category: "DeFi",
    groupId: "Liquity",
  },
  {
    name: "ListaDAO",
    description: "Liquid staking solution for BNB with collateralized debt position protocol for borrowing lisUSD stablecoin against various assets",
    docs: "https://docs.bsc.lista.org/",
    github: "https://github.com/lista-dao",
    category: "DeFi",
    groupId: "ListaDAO",
  },
  {
    name: "Maple",
    description: "Institutional lending platform providing fixed-rate, overcollateralized loans with high yield through Syrup DeFi integration",
    docs: "https://docs.maple.finance/",
    github: "https://github.com/maple-labs",
    category: "DeFi",
    groupId: "Maple",
  },
  {
    name: "mETH Protocol",
    description: "Permissionless, vertically integrated protocol for ETH liquid staking and liquid restaking with enhanced yield opportunities",
    docs: "https://docs.mantle.xyz/meth",
    github: "https://github.com/mantle-lsp",
    category: "DeFi",
    groupId: "mETH",
  },
  {
    name: "Morpho",
    description: "Open decentralized lending network connecting lenders and borrowers with optimized rates and capital efficiency",
    docs: "https://docs.morpho.org/",
    github: "https://github.com/morpho-org",
    category: "DeFi",
    groupId: "Morpho",
  },
  {
    name: "Noir",
    description: "Domain-specific language for zero-knowledge proofs with a simple and expressive syntax",
    docs: "https://noir-lang.org/docs",
    github: "https://github.com/noir-lang/noir",
    category: "Privacy",
    groupId: "Noir",
  },
  {
    name: "OpenZeppelin",
    description: "Battle-tested library of secure, reusable smart contracts and security auditing tools",
    docs: "https://docs.openzeppelin.com/",
    github: "https://github.com/OpenZeppelin/openzeppelin-contracts",
    category: "Security",
    groupId: "OpenZeppelin",
  },
  {
    name: "Ostium",
    description: "Decentralized perpetual exchange on Arbitrum for trading real-world assets including forex, commodities, and stocks",
    docs: "https://ostium-labs.gitbook.io/",
    github: "https://github.com/0xOstium",
    category: "DeFi",
    groupId: "Ostium",
  },
  {
    name: "PancakeSwap",
    description: "Multi-chain decentralized exchange with automated market maker, liquidity pools, and gas-efficient trading infrastructure",
    docs: "https://developer.pancakeswap.finance/",
    github: "https://github.com/pancakeswap/",
    category: "DeFi",
    groupId: "PancakeSwap",
  },
  {
    name: "Peapods",
    description: "Modular DeFi protocol transforming ERC-20 assets into yield-generating pods through volatility farming and lending markets",
    docs: "https://docs.peapods.finance/",
    github: "https://github.com/peapodsfinance/",
    category: "DeFi",
    groupId: "Peapods",
  },
  {
    name: "Pendle Finance",
    description: "Yield trading protocol enabling users to trade, hedge, and leverage yields with capital efficiency",
    docs: "https://docs.pendle.finance/",
    github: "https://github.com/pendle-finance",
    category: "DeFi",
    groupId: "Pendle-Finance",
  },
  {
    name: "Penpie",
    description: "Yield optimizer for Pendle Finance enabling enhanced yields through mPENDLE staking and boosted liquidity provision without vePENDLE locking",
    docs: "https://docs.penpiexyz.io/",
    github: "https://github.com/magpiexyz/",
    category: "DeFi",
    groupId: "Penpie",
  },
  {
    name: "Plasma",
    description: "Blockchain optimized for stablecoin payments with zero-fee USDT transfers, custom gas tokens, and confidential payment support",
    docs: "https://docs.plasma.to/",
    github: null,
    category: "Infrastructure",
    groupId: "Plasma",
  },
  {
    name: "Polymarket",
    description: "Decentralized information markets platform enabling users to trade on the outcomes of real-world events",
    docs: "https://docs.polymarket.com/",
    github: "https://github.com/Polymarket",
    category: "DeFi",
    groupId: "Polymarket",
  },
  {
    name: "Ponder",
    description: "Open-source framework for building blockchain application backends with fast EVM indexing and GraphQL APIs",
    docs: "https://ponder.sh/docs/get-started",
    github: "https://github.com/ponder-sh/ponder",
    category: "Infrastructure",
    groupId: "Pounder",
  },
  {
    name: "Quickswap",
    description: "Multi-chain decentralized exchange offering token swaps, liquidity provision, yield farming, and perpetual trading with low fees",
    docs: "https://docs.quickswap.exchange/",
    github: "https://github.com/QuickSwap",
    category: "DeFi",
    groupId: "Quickswap",
  },
  {
    name: "Raac",
    description: "Real-world asset protocol with lending pools, NFT-based collateral, and oracle-based price discovery for tokenized assets",
    docs: "https://docs.raac.io/",
    github: "https://github.com/RegnumAurumAcquisitionCorp",
    category: "DeFi",
    groupId: "Raac",
  },
  {
    name: "Renzo",
    description: "Liquid restaking protocol simplifying AVS strategies across EigenLayer, Symbiotic, and Jito networks",
    docs: "https://docs.renzoprotocol.com/docs/",
    github: "https://github.com/Renzo-Protocol",
    category: "DeFi",
    groupId: "Renzo",
  },
  {
    name: "Resolv",
    description: "Decentralized stablecoin protocol issuing USR backed by Ethereum and Bitcoin with perpetual futures hedging and insurance mechanisms",
    docs: "https://docs.resolv.xyz/",
    github: "https://github.com/resolv-im",
    category: "DeFi",
    groupId: "Resolv",
  },
  {
    name: "Rocket Pool",
    description: "Decentralized Ethereum staking protocol with permissionless node operation and liquid staking tokens",
    docs: "https://docs.rocketpool.net/",
    github: "https://github.com/rocket-pool/rocketpool",
    category: "DeFi",
    groupId: "RocketPool",
  },
  {
    name: "Sky",
    description: "Decentralized finance ecosystem providing stablecoins, savings, and governance infrastructure, formerly known as MakerDAO",
    docs: "https://sky.money/",
    github: "https://github.com/sky-ecosystem",
    category: "DeFi",
    groupId: "Sky",
  },
  {
    name: "Solidity",
    description: "Object-oriented, high-level language for implementing smart contracts on Ethereum and other EVM chains",
    docs: "https://docs.soliditylang.org/",
    github: "https://github.com/argotorg/solidity",
    category: "Tools",
    groupId: "Solidity",
  },
  {
    name: "Spark Protocol",
    description: "DAI-centered lending and borrowing platform from Sky Ecosystem with capital-efficient liquidity features",
    docs: "https://docs.spark.fi/",
    github: "https://github.com/sparkdotfi",
    category: "DeFi",
    groupId: "Spark",
  },
  {
    name: "Stader",
    description: "Multi-chain liquid staking platform providing staking solutions across Ethereum, Polygon, BNB Chain, and other networks",
    docs: "https://www.staderlabs.com/docs/",
    github: "https://github.com/stader-labs",
    category: "DeFi",
    groupId: "Stader",
  },
  {
    name: "StakeWise",
    description: "Modular liquid staking protocol enabling permissionless vault creation with flexible staking strategies and composable yield",
    docs: "https://docs.stakewise.io/",
    github: "https://github.com/stakewise",
    category: "DeFi",
    groupId: "StakeWise",
  },
  {
    name: "Stream",
    description: "Yield-bearing vault protocol with cross-chain token wrapping and staking infrastructure powered by LayerZero",
    docs: "https://docs.streamprotocol.money/",
    github: "https://github.com/StreamDefi",
    category: "DeFi",
    groupId: "StreamProtocol",
  },
  {
    name: "Superlend",
    description: "Cross-chain lending aggregator optimizing yields across multiple DeFi protocols with automated position management",
    docs: "https://docs.superlend.xyz/",
    github: "https://github.com/Superlend",
    category: "DeFi",
    groupId: "SuperLend",
  },
  {
    name: "Sushi",
    description: "Multi-chain decentralized exchange with automated market maker, concentrated liquidity pools, and cross-chain swap routing",
    docs: "https://docs.sushi.com/",
    github: "https://github.com/sushi-labs",
    category: "DeFi",
    groupId: "SushiSwap",
  },
  {
    name: "Symbiotic",
    description: "Shared security marketplace enabling flexible restaking across multiple networks",
    docs: "https://docs.symbiotic.fi/",
    github: "https://github.com/symbioticfi",
    category: "Infrastructure",
    groupId: "Symbiotic",
  },
  {
    name: "Tenderly",
    description: "Web3 development platform with virtual testnets, transaction simulation, debugging tools, and monitoring across 108+ networks",
    docs: "https://docs.tenderly.co/",
    github: "https://github.com/tenderly",
    category: "Tools",
    groupId: "Tenderly",
  },
  {
    name: "TermMax",
    description: "Next-generation loan AMM offering one-click looping, range orders, and fixed/variable rates with customizable pricing curves",
    docs: "https://docs.ts.finance/",
    github: "https://github.com/term-structure/termmax-contract",
    category: "DeFi",
    groupId: "TermMax",
  },
  {
    name: "The Graph",
    description: "Decentralized protocol for indexing and querying blockchain data with GraphQL",
    docs: "https://thegraph.com/docs/",
    github: "https://github.com/graphprotocol",
    category: "Infrastructure",
    groupId: "TheGraph",
  },
  {
    name: "Tornado Cash",
    description: "Non-custodial privacy protocol enabling permissionless shielded transactions using zero-knowledge proofs and anonymity pools",
    docs: "https://docs.tornado.ws/",
    github: "https://github.com/tornadocash/",
    category: "Privacy",
    groupId: "TornadoCash",
  },
  {
    name: "Uniswap v4",
    description: "Next generation automated market maker with customizable pools through hooks and improved capital efficiency",
    docs: "https://docs.uniswap.org/contracts/v4/overview",
    github: "https://github.com/Uniswap/v4-core",
    category: "DeFi",
    groupId: "Uniswap",
  },
  {
    name: "USDai",
    description: "Synthetic dollar stablecoin backed by T-Bills and tokenized infrastructure loans, offering yield-bearing sUSDai vault tokens",
    docs: "https://docs.usd.ai/",
    github: "https://github.com/metastreet-labs",
    category: "DeFi",
    groupId: "USDai",
  },
  {
    name: "USDX",
    description: "Crypto-native stablecoin using delta-neutral portfolio strategies and multicoin arbitrage, offering yield through sUSDX staking tokens",
    docs: "https://docs.usdx.money/",
    github: "https://github.com/USDXProject",
    category: "DeFi",
    groupId: "USDX",
  },
  {
    name: "Veda",
    description: "Native yield layer providing vault primitives for automated capital deployment and cross-chain DeFi optimization",
    docs: "https://docs.veda.tech/",
    github: "https://github.com/Veda-Labs",
    category: "DeFi",
    groupId: "Veda",
  },
  {
    name: "Venus",
    description: "Decentralized lending and borrowing platform on BNB Chain combining algorithmic money markets with stablecoin minting and risk management",
    docs: "https://docs-v4.venus.io/",
    github: "https://github.com/VenusProtocol/venus-protocol",
    category: "DeFi",
    groupId: "Venus",
  },
  {
    name: "Viem",
    description: "TypeScript interface for Ethereum with composable APIs for JSON-RPC, wallet integration, and smart contract interaction",
    docs: "https://viem.sh/docs/getting-started",
    github: "https://github.com/wevm/viem",
    category: "Tools",
    groupId: "Viem",
  },
  {
    name: "Wormhole",
    description: "Cross-chain messaging protocol for verified message passing and token transfers across blockchains",
    docs: "https://wormhole.com/docs/",
    github: "https://github.com/wormhole-foundation",
    category: "Infrastructure",
    groupId: "Wormhole",
  },
  {
    name: "x402",
    description: "Payment protocol for crypto payments over HTTP using the 402 status code with zero fees and instant settlement",
    docs: "https://docs.cdp.coinbase.com/x402/welcome",
    github: "https://github.com/coinbase/x402",
    category: "Infrastructure",
    groupId: "x402",
  },
  {
    name: "Yearn",
    description: "Yield aggregation protocol with automated vaults deploying capital across DeFi protocols for optimized returns",
    docs: "https://docs.yearn.fi/developers/building-on-yearn",
    github: "https://github.com/yearn",
    category: "DeFi",
    groupId: "Yearn",
  },
  {
    name: "Yield Basis",
    description: "Autoleverage automated market maker protocol providing leveraged liquidity tokens with capital-efficient yield strategies",
    docs: "https://docs.yieldbasis.com/",
    github: "https://github.com/yield-basis",
    category: "DeFi",
    groupId: "YieldBasis",
  },
  {
    name: "Zircuit",
    description: "EVM-compatible zero-knowledge rollup with sequencer-level security for proactive protection and fast finality",
    docs: "https://docs.zircuit.com/",
    github: "https://github.com/zircuit-labs",
    category: "Infrastructure",
    groupId: "Zircuit",
  },
  {
    name: "ZeroDev",
    description: "Smart account platform supporting ERC-4337 and EIP-7702 with passkey authentication, gas sponsorship, and cross-chain functionality",
    docs: "https://docs.zerodev.app/",
    github: "https://github.com/zerodevapp",
    category: "Infrastructure",
    groupId: "ZeroDev",
  },
];
